// <a href="https://ibb.co/DfcDW1z"><img src="https://i.ibb.co/HTwD4KB/dish-brush.jpg" alt="dish-brush" border="0"></a>
// <a href="https://ibb.co/G3Zx8rw"><img src="https://i.ibb.co/tP0mv1f/diswash-liquid.jpg" alt="diswash-liquid" border="0"></a>

export const getFlashSaleData = () => {
    return [
        {
            id: 1,
            name: "Dishwashing Liquid",
            description: "Powerful dishwashing liquid for tough grease",
            price: 5.99,
            imageUrl: "https://i.ibb.co/HTwD4KB/dish-brush.jpg",
            flashSale: true,
            createdAt: new Date("2024-03-24T08:00:00Z"),
        },
        {
            id: 2,
            name: "Dishwasher Detergent",
            description: "Effective detergent for automatic dishwashers",
            price: 9.99,
            imageUrl: "https://i.ibb.co/HTwD4KB/dish-brush.jpg",
            flashSale: true,
            createdAt: new Date("2024-03-24T08:15:00Z"),
        },
        {
            id: 3,
            name: "Scouring Pads",
            description: "Non-scratch scouring pads for tough stains",
            price: 3.49,
            imageUrl: "https://i.ibb.co/HTwD4KB/dish-brush.jpg",
            flashSale: true,
            createdAt: new Date("2024-03-24T08:30:00Z"),
        },
        {
            id: 4,
            name: "Glass Cleaner",
            description: "Streak-free glass cleaner for sparkling surfaces",
            price: 4.99,
            imageUrl: "https://i.ibb.co/HTwD4KB/dish-brush.jpg",
            flashSale: true,
            createdAt: new Date("2024-03-24T08:45:00Z"),
        },
        {
            id: 5,
            name: "All-Purpose Cleaner",
            description: "Versatile cleaner for various surfaces",
            price: 6.49,
            imageUrl: "https://i.ibb.co/HTwD4KB/dish-brush.jpg",
            flashSale: true,
            createdAt: new Date("2024-03-24T09:00:00Z"),
        },
        {
            id: 6,
            name: "Dishwashing Liquid",
            description: "Powerful dishwashing liquid for tough grease",
            price: 5.99,
            imageUrl: "https://i.ibb.co/tP0mv1f/diswash-liquid.jpg",
            flashSale: true,
            createdAt: new Date("2024-03-24T08:00:00Z"),
        },
        {
            id: 7,
            name: "Dishwasher Detergent",
            description: "Effective detergent for automatic dishwashers",
            price: 9.99,
            imageUrl: "https://i.ibb.co/tP0mv1f/diswash-liquid.jpg",
            flashSale: true,
            createdAt: new Date("2024-03-24T08:15:00Z"),
        },
        {
            id: 8,
            name: "Scouring Pads",
            description: "Non-scratch scouring pads for tough stains",
            price: 3.49,
            imageUrl: "https://i.ibb.co/tP0mv1f/diswash-liquid.jpg",
            flashSale: true,
            createdAt: new Date("2024-03-24T08:30:00Z"),
        },
        {
            id: 9,
            name: "Glass Cleaner",
            description: "Streak-free glass cleaner for sparkling surfaces",
            price: 4.99,
            imageUrl: "https://i.ibb.co/tP0mv1f/diswash-liquid.jpg",
            flashSale: true,
            createdAt: new Date("2024-03-24T08:45:00Z"),
        },
        {
            id: 10,
            name: "All-Purpose Cleaner",
            description: "Versatile cleaner for various surfaces",
            price: 6.49,
            imageUrl: "https://i.ibb.co/tP0mv1f/diswash-liquid.jpg",
            flashSale: true,
            createdAt: new Date("2024-03-24T09:00:00Z"),
        },

    ];
};
